# action.yml
name: 'Github action deployer'
description: 'Runs deployer deploy'
inputs:
  deployerFileLocation:  # id of input
    description: 'Path of the deployer file in repository'
    required: true
    default: '/.deployment/deploy.php'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - ${{ inputs.deployer-args }}
