# action.yml
name: 'Github action deployer'
description: 'Runs deployer deploy'
inputs:
  deployer-args:  # id of input
    description: 'Arguments for deployer'
    required: true
    default: '--file=./deploy.php -v deploy staging'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deployer-args }}
